# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Send deploy request
        run: curl -X POST -H "Content-Type application/json"
          -d '{"secretKey":"${{ secrets.DEPLOY_KEY}}"}'
          http://vtog.vesper.host:3000/deploy
